server:
  port: 9090

kafka:
  bootstrap-servers: "localhost:9092"
  sampletopic: "datatopic"
  samplegroupId: "groupId"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rootrewansh
    driver-class-name: org.postgresql.Driver
