server:
  port: 9090

kafka:
  bootstrap-servers: "localhost:9092"
  sampletopic: "datatopic"
  samplegroupId: "groupId"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rootrewansh
  jpa:
    hibernate:
      ddl-auto: update   # Or create-drop for dev
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

        format_sql: true
        show_sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE

